### ISSUE TITLE
Customized ROS msg does not work on FIROS

### ISSUE THREAD

**Issue by rafluq** [w4bo/fiware-demo#23]
Hi! I would like to ask if you could help me with one problem. I'm looking at your demo4-robot in order to launch my own package with FIWARE and FIROS.

My package is called "test" and it only runs a chatter publisher which publishes my own customized ROS msg called "Test.msg" which contains only a float64 field. I have copied the message file at catkin_ws/src/firos/msgs/test/Tesg.msg. Finally I have compiled both my package and firos package with this configuration at topics.json:

```
{
    "/chatter": ["test/Test", "subscriber"]
}
```

However, firos arises the following error:

> Max retries exceeded with url: /v2/entities/.chatter (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7bbc0dab50>: Failed to establish a new connection: [Errno -2] Name or service not known',))

Do I need to make any other change at firos package? Thank you in advance!

**Comment by w4bo** [comment]
Hi @rafluq ,

Unfortunately we can only help you with issues about our repo (e.g., if you encounter reproducibility issues with our demos). 
Therefore I am closing this issue. 

Sorry.
